export const DID_MOUNT = 'DID_MOUNT';
export const DISPLAY_INDICATOR = 'DISPLAY_INDICATOR';

export const LOADING_ARTICLE = 'LOADING_ARTICLE';
export const LOADED_ARTICLES = 'LOADED_ARTICLES';
export const LOADED_ARTICLE = 'LOADED_ARTICLE';
export const TYPING_ARTICLE = 'TYPING_ARTICLE';
export const SAVING_ARTICLE = 'SAVING_ARTICLE';
export const SAVED_ARTICLE = 'SAVED_ARTICLE';
export const DESTROY_ARTICLE = 'DESTROY_ARTICLE';

export const LOADING_CATEGORIES = 'LOADING_CATEGORIES';
export const LOADED_CATEGORIES = 'LOADED_CATEGORIES';
export const LOADING_TAGS = 'LOADING_TAGS';
export const LOADED_TAGS = 'LOADED_TAGS';

export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
