export const LOADING_ARTICLE = 'LOADING_ARTICLE';
export const LOADED_ARTICLE = 'LOADED_ARTICLE';
export const TYPING_ARTICLE = 'TYPING_ARTICLE';
export const SAVING_ARTICLE = 'SAVING_ARTICLE';
export const DESTROY_ARTICLE = 'DESTROY_ARTICLE';
